services:

  notebook:
    restart: always
    image: camargog95/tcc:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'notebook'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - '8888:8888'
      - '8088:8088'
    volumes:
      - './:/tf'
      - '/home/gc/Documents/HDD/TCC/:/tf/Dados'
    environment:
      - JUPYTER_PATH=/tf/utils/
      - TF_CPP_MIN_LOG_LEVEL=3
      - TF_FORCE_GPU_ALLOW_GROWTH=true
      - TF_MIN_GPU_MULTIPROCESSOR_COUNT=3